[package]
version = "0.0.0"
authors = [
  "nickray <n@stalder.io>",
]
description   = "Hardware Abstraction Layer (HAL) for the NXP LPC55S6x ARM Cortex-33 microcontrollers"
documentation = "https://docs.rs/lpc55s6x-hal"
keywords = ["no-std", "cortex-m", "nxp", "lpc", "embedded-hal-impl"]
license = "MIT OR Apache-2.0"
name = "lpc55s6x-hal"
repository = "https://github.com/nickray/lpc55s6x-hal"
edition = "2018"

[dependencies]
bare-metal = "0.2.4"
vcell = "0.1"

cortex-m = ">= 0.5.8, < 0.7"
embedded-hal = { version = "0.2", features = ["unproven"] }
lpc55s6x-pac = "0.0.1"
nb = "0.1.1"

[dev-dependencies]
cortex-m-rt = "0.6.10"
panic-halt  = "0.2.0"
panic-semihosting = "0.5.2"
# cortex-m-semihosting = "0.3.3"

[dev-dependencies.cortex-m-semihosting]
git = "https://github.com/rust-embedded/cortex-m-semihosting"
rev = "25cb5534bf59ead415c23f37f88d986209c698e3"
features = ["jlink-quirks"]

[features]
# default-features = ["rt"]
rt = ["lpc55s6x-pac/rt"]
# Boards
lpcxpresso55s69 = []
solo = []
