[package]
name = "lpc55s6x-hal"
version = "0.0.2"
edition = "2018"
description   = "Hardware Abstraction Layer (HAL) for the NXP LPC55S6x ARM Cortex-33 microcontrollers"
repository = "https://github.com/nickray/lpc55s6x-hal"
license = "Apache-2.0 OR MIT"
readme = "README.md"
documentation = "https://docs.rs/lpc55s6x-hal"
keywords = ["no-std", "cortex-m", "nxp", "lpc", "embedded-hal-impl"]
categories = ["embedded", "no-std"]
authors = ["Nicolas Stalder <n@stalder.io>", "Hanno Braun <hanno@braun-robotics.com>"]
build = "build.rs"

[badges]
circle-ci = { repository = "nickray/lpc55s6x-hal" }

[dependencies]
bare-metal = "0.2"
cortex-m = "0.6"
cortex-m-semihosting = "0.3"
embedded-hal = { version = "0.2", features = ["unproven"] }
# generic-array = "0.13.2"
lpc55s6x-pac = "0.0.5"

nb = "0.1"
# nom = { version = "^5", default-features = false }
usb-device = "0.2.3"
usbd-serial = "0.1.0"
vcell = "0.1.2"
void = { version = "1", default-features = false }

[dev-dependencies]
aes-soft = "0.3"
cortex-m-rt = "0.6"
cortex-m-rtfm = "0.5.0-beta.1"
cortex-m-semihosting = "0.3"
heapless = "0.5"
panic-halt  = "0.2"
panic-semihosting = { version = "0.5", features = ["jlink-quirks"] }
ssd1306 = "0.3.0-alpha.2"

[features]
default = ["rt"]
rt = ["lpc55s6x-pac/rt"]
# # Boards
# lpcxpresso55s69 = []
# solo = []

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = "z"
